FROM node:12.22.1

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

## add `/app/node_modules/.bin` to $PATH
## ENV PATH /app/node_modules/.bin:$PATH

## install and cache app dependencies 
# COPY frontend/package.json / app/package.json

# RUN npm install 
## RUN npm install @vue/cli@3.7.9 -g

EXPOSE 8080

CMD ["npm", "run", "serve"]





